# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fad5e090651198604b82cc80c4fe6c6e40e9d94f090bf4b6da9fcebbd0b6b43b2ea78a332b82f35b1fca36f6357bbb0f8bb22b25a852c487b3866aaea133d391

test:
  secret_key_base: eb8b5e5deb0373cc7f90428e24417a1a4b4028f09a7ff284ea0d958662412e0706fc5f9c6c8edd95fc14b855ad7d8d6dfc1d6d9ea4908d9d40453e0e932ff454

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
